apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv-volume2
