apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
#  storageClassName: local-storage
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv-volume

#  rbd:
#    image: foo
#    monitors:
#      # 使用 kubectl get pods -n rook-ceph 查看 rook-ceph-mon- 开头的 POD IP 即可得下面的列表
#      - '10.16.154.78:6789'
#      - '10.16.154.82:6789'
#      - '10.16.154.83:6789'
#    pool: kube
#    fsType: ext4
#    readOnly: true
#    user: admin
#    keyring: /etc/ceph/keyring