apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
#  storageClassName: local-storage
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi